spring.application.name=buziahub-api
spring.config.import=optional:file:.env.properties

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.profiles.active=${APP_PROFILE:default}
app.seed.cleanup-on-default-startup=true

spring.jpa.hibernate.ddl-auto=update

seed.count=10000
seed.random-seed=42
seed.clear-existing=true

# Logging - keep it clean
logging.level.root=WARN
logging.level.com.buziahub=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO

# Only enable SQL logging in test profile
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false